### ISSUE TITLE
mail: use type aliases for Address

### ISSUE THREAD

**Issue by emersion** [emersion/go-message#11]
Waiting for Go 1.9.

**Comment by brunnre8** [comment]
been a while :)
I think this can be closed?

**Comment by foxcpp** [comment]
It is still not implemented, it you want it - make a PR, I suppose?

**Comment by brunnre8** [comment]
so, did my legwork.

Did you think about how this could work?
Based on https://github.com/golang/proposal/blob/master/design/18130-type-alias.md and https://talks.golang.org/2016/refactor.article plus reading the language spec I can't see a way of using type aliases.

The problem boils down to this (highlight is mine):
`type T1 = T2`  
Since T1 is just another way to write T2, it does not have its own set of method declarations. Instead, T1’s method set is the same as T2’s. At least for the initial trial, there is no restriction against method declarations using T1 as a receiver type, provided using T2 in the same declaration would be valid. **Note that if T1 is an alias for a type T2 defined in an imported package, method declarations using T1 as a receiver type are invalid, just as method declarations using T2 as a receiver type are invalid.**

So as net/mail.Address is a non local type we can't assign methods to it. Trying yields errors like `mail/header.go:271:6: cannot define new methods on non-local type message.Header`

What am I missing?

**Comment by emersion** [comment]
>So as net/mail.Address is a non local type we can't assign methods to it

Yeah. But we don't need to. The only method we define on our `Address` type is `String`, which `net/mail` already has.

**Comment by brunnre8** [comment]
Ah I see. thanks

**Comment by brunnre8** [comment]
Do you want to deprecate the use of mail.Address in favor of net/mail.Address or would you rather keep the alias as the preferred version so that people only have to import go-message/mail? I think keeping it as the canonical source does make more sense.

Also, would you mind if I send a PR exporting the parse address list function? That is the one thing we still need from net/mail in aerc.... that would save us the annoying import renaming due to the name clash

**Comment by emersion** [comment]
Posted some details on aerc's mailing list: https://lists.sr.ht/~sircmpwn/aerc/%3C20201108152314.629758-1-reto%40labrat.space%3E#%3CPQlfIPyCDcKQR_a83X_sit3ouFun2ciQAJGk_9Q3LERQ262tAa2FPeGWlx_2WbgJs_NCxBgCPhm1mG8omfJ2m7OBkO71nxbf4ImkTbmIYSc=@emersion.fr%3E
