### ISSUE TITLE
How to read an attachment?

### ISSUE THREAD

**Issue by SUP3RIA** [emersion/go-message#12]
Could I ask for an example how to save an attachment to disk or as byte string?

I know that the name of an attachment can be obtained with something like this

```go
	case mail.AttachmentHeader:
			// This is an attachment
			filename, _ := h.Filename()
			log.Println(filename)
```

thx

**Comment by emersion** [comment]
It works the same way as reading a message text part body: `p.Body` is an `io.Reader`.

**Comment by tappoz** [comment]
@emersion coming from https://github.com/emersion/go-imap here.

It looks like the way someone should filter/get messages and their parts (To/From, Subject, Body, Attachments) is a bit convoluted, perhaps due to the IMAP standard itself, but I am not sure.

I am facing a similar problem here and need to store to file / process as byte string an attachment of type xlsm (Microsoft Excel).

The example here: https://github.com/emersion/go-imap/wiki/Fetching-messages#fetching-the-whole-message-body gives back the filename of the attachment, but I get lost when trying to get back the content of that file. Looking at the source code fo this https://godoc.org/github.com/emersion/go-message#Header it seems someone needs to play around with get/set maps that perhaps represent the IMAP standard/terminology, but I am not sure which IMAP "key strings" I should use in order to retrieve from that key/value map the content of the attachment.

Having an example in the docs could help in avoiding to go through the source code. Many thanks :)

**Comment by emersion** [comment]
To get the content, you can do this (which is done for the body of the message in the wiki):

```go
b, _ := ioutil.ReadAll(p.Body)
```

Of course if you have a function that expects an `io.Reader` it's better to just use `p.Body` without `ioutil.ReadAll`.

Pull requests welcome to improve examples.

**Comment by slaterx** [comment]
I've managed to download an attachment using the following snippet:

```
case *mail.AttachmentHeader:
					// This is an attachment
					filename, _ := h.Filename()
					log.Printf("Got attachment: %v\n", filename)
					// Create file with attachment name
					file, err := os.Create(filename)
					if err != nil {
						log.Fatal(err)
					}
					// using io.Copy instead of io.ReadAll to avoid insufficient memory issues
					size, err := io.Copy(file, p.Body)
					if err != nil {
						log.Fatal(err)
					}
					log.Printf("Saved %v bytes into %v\n", size, filename)
```

Let me know which file has the examples for attachments and I'll make a PR.

**Comment by bzsozsy** [comment]
Guys I'm just curious if is there a easier way to check if the email has an attachments? I developing a small CRM and would like to show an email list like: 

From | Subject | Date | Size | HasItAttachment(true or false)

Do I have to Fetch the whole message body to check if it has an attachment?

**Comment by emersion** [comment]
No. You should fetch the body structure instead.

https://git.sr.ht/~emersion/koushin/tree/master/plugins/base/imap.go#L147

**Comment by till** [comment]
@emersion Sorry for reviving this, but can you add an example somewhere how to work with v2 of your go-imap lib and achieve something similar?

**Comment by ogundiyantobiloba** [comment]
@emersion please can you add an example how to download attachment from your imap version 2 library.
