### ISSUE TITLE
Commit our enhancement back to go standard library

### ISSUE THREAD

**Issue by digitive** [emersion/go-message#63]
Hi, I think our implementation of textproto.Header struct is more advanced than the go standard textproto.MIMEHeader (which is a map[string][]string), especially in the way of keeping the original raw headers ( necessary for DKIM ). Is it possible for us to submit a change request to the golang project, to make it be part of the go standard library to replace the textproto.MIMEHeader? In this way, we don't have to have copy of the multipart.go, also will get benefits for golang bug fixes.

**Comment by foxcpp** [comment]
There is a non-zero performance cost in keeping a much more complex structure to preserve the order and original format of the header. I don't think all users should pay it, especially since most of them don't care about ordering or whitespace. Additionally, this would be a breaking change to replace MINEHeader.

**Comment by foxcpp** [comment]
There is a benchmark in our textproto subpackage, you can run it to see the difference between the standard library and go-message. So far I believe there is no simple way to improve it while keeping ordering and original formatting.

**Comment by digitive** [comment]
Right. Then we should sync our version of multipart.go with the std lib to get bugfixes.
